define(
[],
function()
{
    var xhrData = {

        token:
        {
            access_token: "fakeToken",
            expires_in: 31536000,
            refresh_token: "otherFakeToken",
            scope: "fitness clientevents users athletes exerciselibrary images",
            token_type: "bearer"
        },

        athleteSettings:
        {
            barbkprem:
            {
                "athleteId": 426489,
                "userName": null,
                "birthday": null,
                "gender": null,
                "email": null,
                "address": null,
                "address2": null,
                "city": null,
                "state": null,
                "country": null,
                "zipCode": null,
                "phone": null,
                "cellPhone": null,
                "profilePhotoUrl": null,
                "age": null,
                "units": 0,
                "dateFormat": null,
                "timeZone": null,
                "isAthlete": true,
                "heartRateZones": [{ "threshold": 110,
                    "maximumHeartRate": 160,
                    "restingHeartRate": 15,
                    "workoutTypeId": 0,
                    "zones": [{ "label": "Zone 1: Recovery",
                        "maximum": 127,
                        "minimum": 99 },
                    { "label": "Zone 2: Aerobic",
                        "maximum": 136,
                        "minimum": 128 },
                    { "label": "Zone 3: Tempo",
                        "maximum": 143,
                        "minimum": 137 },
                    { "label": "Zone 4: SubThreshold",
                        "maximum": 149,
                        "minimum": 144 },
                    { "label": "Zone 5A: SuperThreshold",
                        "maximum": 153,
                        "minimum": 150 },
                    { "label": "Zone 5B: Aerobic Capacity",
                        "maximum": 158,
                        "minimum": 154 },
                    { "label": "Zone 5C: Anaerobic Capacity",
                        "maximum": 166,
                        "minimum": 159 }] }],
                "powerZones": [{ "threshold": 110,
                    "workoutTypeId": 0,
                    "zones": [{ "label": "1",
                        "maximum": 89,
                        "minimum": 0 },
                    { "label": "2",
                        "maximum": 121,
                        "minimum": 90 },
                    { "label": "3",
                        "maximum": 145,
                        "minimum": 122 },
                    { "label": "4",
                        "maximum": 169,
                        "minimum": 146 },
                    { "label": "5",
                        "maximum": 193,
                        "minimum": 170 },
                    { "label": "6",
                        "maximum": 2000,
                        "minimum": 194 }] }],
                "speedZones": [{ "workoutTypeId": 0,
                    "zones": [] },
                { "workoutTypeId": 1,
                    "zones": [{ "label": "Zone 1",
                        "maximum": 0.819672131147541,
                        "minimum": 0.1111111111111111 },
                    { "label": "Zone 2",
                        "maximum": 0.86956521739130432,
                        "minimum": 0.819672131147541 },
                    { "label": "Zone 3",
                        "maximum": 0.93457943925233644,
                        "minimum": 0.86956521739130432 },
                    { "label": "Zone 4",
                        "maximum": 0.99009900990099009,
                        "minimum": 0.93457943925233644 },
                    { "label": "Zone 5a",
                        "maximum": 1.0309278350515465,
                        "minimum": 0.99009900990099009 },
                    { "label": "Zone 5b",
                        "maximum": 1.1111111111111112,
                        "minimum": 1.0309278350515465 },
                    { "label": "Zone 5c",
                        "maximum": 100.0,
                        "minimum": 1.1111111111111112 }] },
                { "workoutTypeId": 2,
                    "zones": [{ "label": "Zone 1",
                        "maximum": 0.819672131147541,
                        "minimum": 0.1111111111111111 },
                    { "label": "Zone 2",
                        "maximum": 1.1111111111111112,
                        "minimum": 1.0309278350515465 },
                    { "label": "Zone 3",
                        "maximum": 0.93457943925233644,
                        "minimum": 0.86956521739130432 },
                    { "label": "Zone 4",
                        "maximum": 0.99009900990099009,
                        "minimum": 0.93457943925233644 },
                    { "label": "Zone 5a",
                        "maximum": 1.0309278350515465,
                        "minimum": 0.99009900990099009 },
                    { "label": "Zone 5b",
                        "maximum": 1.1111111111111112,
                        "minimum": 1.0309278350515465 },
                    { "label": "Zone 5c",
                        "maximum": 100.0,
                        "minimum": 1.1111111111111112 }] },
                { "workoutTypeId": 3,
                    "zones": [{ "label": "Zone 1",
                        "maximum": 1.73228000346456,
                        "minimum": 0.0 },
                    { "label": "Zone 2",
                        "maximum": 1.9602704039205407,
                        "minimum": 1.73228000346456 },
                    { "label": "Zone 3",
                        "maximum": 2.1100288042200575,
                        "minimum": 1.9602704039205407 },
                    { "label": "Zone 4",
                        "maximum": 2.2352000044704,
                        "minimum": 2.1100288042200575 },
                    { "label": "Zone 5a",
                        "maximum": 2.3089616046179229,
                        "minimum": 2.2352000044704 },
                    { "label": "Zone 5b",
                        "maximum": 2.4900128049800259,
                        "minimum": 2.3089616046179229 },
                    { "label": "Zone 5c",
                        "maximum": 1609.344,
                        "minimum": 2.4900128049800259 }] },
                { "workoutTypeId": 13,
                    "zones": [{ "label": "Zone 1",
                        "maximum": 1.73228000346456,
                        "minimum": 0.0 },
                    { "label": "Zone 2",
                        "maximum": 1.9602704039205407,
                        "minimum": 1.73228000346456 },
                    { "label": "Zone 3",
                        "maximum": 2.1100288042200575,
                        "minimum": 1.9602704039205407 },
                    { "label": "Zone 4",
                        "maximum": 2.2352000044704,
                        "minimum": 2.1100288042200575 },
                    { "label": "Zone 5a",
                        "maximum": 2.3089616046179229,
                        "minimum": 2.2352000044704 },
                    { "label": "Zone 5b",
                        "maximum": 2.4900128049800259,
                        "minimum": 2.3089616046179229 },
                    { "label": "Zone 5c",
                        "maximum": 1609.344,
                        "minimum": 2.4900128049800259 }] }]
            }

        },

        equipment:
        {
            barbkprem: [
                {
                    equipmentId: 125,
                    name: "My Other Bike",
                    notes: "",
                    brand: "Schwinn",
                    model: "Stingray",
                    dateOfPurchase: "12/20/1973",
                    athleteId: 426489,
                    retired: false,
                    retiredDate: null,
                    isDefault: false,
                    startingDistance: 0,
                    actualDistance: 1000,
                    crankLengthMillimeters: "155",
                    wheels: "training",
                    maxDistance: null,
                    type: 1        
                },
                {
                    equipmentId: 124,
                    name: "Speed 007",
                    notes: "It's great!",
                    brand: "Cyclery",
                    model: "Speed",
                    dateOfPurchase: "12/20/2013",
                    athleteId: 426489,
                    retired: false,
                    retiredDate: null,
                    isDefault: true,
                    startingDistance: 0,
                    actualDistance: 1609.344,
                    crankLengthMillimeters: "172.5",
                    wheels: "2 or more",
                    maxDistance: null,
                    type: 1        
                },
                {
                    equipmentId: 126,
                    name: "Snowshoes",
                    notes: "for when it snows",
                    brand: "REI",
                    model: "snowshoe",
                    dateOfPurchase: "12/20/2012",
                    athleteId: 426489,
                    retired: false,
                    retiredDate: null,
                    isDefault: false,
                    startingDistance: 0,
                    actualDistance: 2,
                    crankLengthMillimeters: null,
                    wheels: null,
                    maxDistance: 500,
                    type: 2        
                },
                {
                    equipmentId: 123,
                    name: "Awesome Shoe 9000",
                    notes: "It's great!",
                    brand: "Shoe Factory",
                    model: "9000",
                    dateOfPurchase: "12/20/2013",
                    athleteId: 426489,
                    retired: false,
                    retiredDate: null,
                    isDefault: true,
                    startingDistance: 0,
                    actualDistance: 1609.344,
                    crankLengthMillimeters: null,
                    wheels: null,
                    maxDistance: 500,
                    type: 2        
                }
            ]
        },

        users:
        {
            barbkprem:
            {
                "userId": 426489,
                "firstName": "Barbara prem",
                "lastName":"Kauffman",
                "userName":"barbkprem",
                "birthday":"1966-07-26T00:00:00",
                "gender":null,
                "email":"barbara@peaksware.com",
                "address":null,
                "address2":null,
                "city":"fort lupton",
                "state":"CO",
                "country":"",
                "zipCode":"",
                "phone":null,
                "cellPhone":null,
                "profilePhotoUrl":"/TPWebServices/GetImageFile.aspx?t=db&i=502e9e5717044a137867e211&f=426489_1255469787_17_8_2012.jpg",
                "age":46,
                "units":1,
                "dateFormat":"mdy",
                "timeZone":"US/Mountain",
                "story":"Here is my profile information",
                "longitude":null,
                "latitude":null,
                "language":"en-us",
                "settings":
                {
                    "account":
                        {
                            "accessGroupIds": [999999],
                            "headerImageUrl":"/TPWebServices/GetImageFile.aspx?t=db&i=4fda2babbc3fc714fc11de99&f=training_peaks_banner.png",
                            "headerLink": "http://www.trainingpeaks.com",
                            "isCoach":false,
                            "isCoached":false,
                            "shouldCompleteProfile": false
                        },
                    "affiliate":
                        {
                            "code":"trainingpeaks3",
                            "isTrainingPeaks":true
                        },
                    "calendar":
                        {
                            "numberOfWeeksToShow":3,
                            "showWeekSummary":true,
                            "showWorkouts":true,
                            "showMeals":true,
                            "showIcons":true,
                            "showMetrics":true,
                            "workoutColorization":1,
                            "display":1,
                            "workoutLabelLayout":[23,
                            30,
                            7,
                            31,
                            35,
                            8,
                            5]
                        },
                    dashboard: {
                        dateOptions: {
                            startDate: null,
                            endDate: null,
                            quickDateSelectOption: null
                        },
                        pods: []
                    },
                    "workout":
                        {
                            "layout":{"1":[1,2,4,5,9,10,3,12,19,17,22],"2":[1,2,3,5,6,9,10,8,11,7,13,14,15,16,17,18,20,21,22],"3":[1,2,4,5,6,9,10,7,8,3,19,13,20,14,15,16,17,18,21,22],"4":[1,2,3,4,5,6,9,10,7,8,14,19,13,22],"5":[1,2,5,9,10,13,22],"6":[1,2,13,22],"7":[1,13,22],"8":[1,2,3,5,6,9,10,8,13,4,14,22],"9":[1,5,9,10,13,22],"10":[1,2,5,9,10,13,21,22],"11":[1,2,4,5,9,10,13,21,22],"12":[1,2,4,5,6,9,10,12,11,13,17,20,15,22],"13":[1,2,4,5,6,9,10,13,22],"100":[1,2,5,9,10,13,22]}
                        },
                    "metrics": [{"type":9,
                        "public":false},
                    {"type":6,
                        "public":false},
                    {"type":10,
                        "public":true},
                    {"type":11,
                        "public":true},
                    {"type":2,
                        "public":false},
                    {"type":7,
                        "public":false},
                    {"type":3,
                        "public":false},
                    {"type":8,
                        "public":false},
                    {"type":20,
                        "public":false},
                    {"type":4,
                        "public":false},
                    {"type":5,
                        "public":false},
                    {"type":1,
                        "public":false},
                    {"type":12,
                        "public":false},
                    {"type":55,
                        "public":false},
                    {"type":53,
                        "public":false},
                    {"type":50,
                        "public":false},
                    {"type":49,
                        "public":false},
                    {"type":47,
                        "public":false},
                    {"type":48,
                        "public":false},
                    {"type":46,
                        "public":false},
                    {"type":56,
                        "public":true},
                    {"type":57,
                        "public":true},
                    {"type":51,
                        "public":true},
                    {"type":23,
                        "public":true},
                    {"type":59,
                    "public": true
                    }]
                },
                "athletes": [{
                    "athleteId": 426489,
                    "firstName":"Barbara prem",
                    "lastName":"Kauffman",
                    "athleteType":3,
                    "userType":4,
                    "category": "",
                    "lastLogin": "2013-05-07T16:30:53",
                    "lastPlannedWorkout":"3911-03-08T00:00:00",
                    "settings":null,
                    "profilePhotoUrl":"/TPWebServices/GetImageFile.aspx?t=db&i=502e9e5717044a137867e211&f=426489_1255469787_17_8_2012.jpg"}
                ]
            }, // END BARBKPREM

            supercoach:
            {
                "userId": 12345678,
                "firstName": "Super",
                "lastName": "Coach",
                "userName": "supercoach",
                "birthday":"1966-07-26T00:00:00",
                "gender":null,
                "email":"coach@peaksware.com",
                "address":null,
                "address2":null,
                "city":"fort lupton",
                "state":"CO",
                "country":"",
                "zipCode":"",
                "phone":null,
                "cellPhone":null,
                "profilePhotoUrl":"/TPWebServices/GetImageFile.aspx?t=db&i=502e9e5717044a137867e211&f=426489_1255469787_17_8_2012.jpg",
                "age":46,
                "units": 1,
                "dateFormat": "mdy",
                "timeZone":"US/Mountain",
                "story":"Here is my profile information",
                "longitude":null,
                "latitude":null,
                "language":"en-us",
                "isAthlete": false,
                "settings":
                {
                    "account":
                        {
                            "accessGroupIds": [999999],
                            "headerImageUrl":"/TPWebServices/GetImageFile.aspx?t=db&i=4fda2babbc3fc714fc11de99&f=training_peaks_banner.png",
                            "headerLink": "http://www.trainingpeaks.com",
                            "isCoach": true,
                            "coachType": 1,
                            "isCoached":false,
                            "shouldCompleteProfile":false
                        },
                    "affiliate":
                        {
                            "code":"trainingpeaks3",
                            "isTrainingPeaks":true
                        },
                    "calendar":
                        {
                            "numberOfWeeksToShow":3,
                            "showWeekSummary":true,
                            "showWorkouts":true,
                            "showMeals":true,
                            "showIcons":true,
                            "showMetrics":true,
                            "workoutColorization":1,
                            "display":1,
                            "workoutLabelLayout":[23,
                            30,
                            7,
                            31,
                            35,
                            8,
                            5]
                        },
                    "workout":
                        {
                            "layout":{"1":[1,2,4,5,9,10,3,12,19,17,22],"2":[1,2,3,5,6,9,10,8,11,7,13,14,15,16,17,18,20,21,22],"3":[1,2,4,5,6,9,10,7,8,3,19,13,20,14,15,16,17,18,21,22],"4":[1,2,3,4,5,6,9,10,7,8,14,19,13,22],"5":[1,2,5,9,10,13,22],"6":[1,2,13,22],"7":[1,13,22],"8":[1,2,3,5,6,9,10,8,13,4,14,22],"9":[1,5,9,10,13,22],"10":[1,2,5,9,10,13,21,22],"11":[1,2,4,5,9,10,13,21,22],"12":[1,2,4,5,6,9,10,12,11,13,17,20,15,22],"13":[1,2,4,5,6,9,10,13,22],"100":[1,2,5,9,10,13,22]}
                        },
                    "metrics": [{"type":9,
                        "public":false},
                    {"type":6,
                        "public":false},
                    {"type":10,
                        "public":true},
                    {"type":11,
                        "public":true},
                    {"type":2,
                        "public":false},
                    {"type":7,
                        "public":false},
                    {"type":3,
                        "public":false},
                    {"type":8,
                        "public":false},
                    {"type":20,
                        "public":false},
                    {"type":4,
                        "public":false},
                    {"type":5,
                        "public":false},
                    {"type":1,
                        "public":false},
                    {"type":12,
                        "public":false},
                    {"type":55,
                        "public":false},
                    {"type":53,
                        "public":false},
                    {"type":50,
                        "public":false},
                    {"type":49,
                        "public":false},
                    {"type":47,
                        "public":false},
                    {"type":48,
                        "public":false},
                    {"type":46,
                        "public":false},
                    {"type":56,
                        "public":true},
                    {"type":57,
                        "public":true},
                    {"type":51,
                        "public":true},
                    {"type":23,
                        "public":true},
                    {"type":59,
                    "public": true
                    }]
                },
                "athletes": [
                    {
                        "athleteId": 12345,
                        "firstName": "Athlete",
                        "lastName": "One",
                        "athleteType": 3,
                        "userType": 4,
                        "category": "",
                        "lastLogin": "2013-05-07T16:30:53",
                        "lastPlannedWorkout": "3911-03-08T00:00:00",
                        "settings": null,
                        "profilePhotoUrl": "/TPWebServices/GetImageFile.aspx?t=db&i=502e9e5717044a137867e211&f=426489_1255469787_17_8_2012.jpg"
                    },
                    {
                    "athleteId": 23456,
                    "firstName":"Another",
                    "lastName":"Athlete",
                    "athleteType":3,
                    "userType":4,
                    "category": "",
                    "lastLogin": "2013-05-07T16:30:53",
                    "lastPlannedWorkout":"3911-03-08T00:00:00",
                    "settings":null,
                    "profilePhotoUrl":"/TPWebServices/GetImageFile.aspx?t=db&i=502e9e5717044a137867e211&f=426489_1255469787_17_8_2012.jpg"}
                ]
            } // END SUPERCOACH

        },

        trainingPlans: [

            {
                planId: 1,
                title: "Training Plan One"
            },
            {
                planId: 2,
                title: "Training Plan Two"
            },
            {
                planId: 3,
                title: "Training Plan Three",
            }

        ],

        trainingPlanDetails: {
            author: "Some Guy",
            dayCount: 365,
            description: "Description of a training plan",
            eventDate: "2013-12-25",
            eventName: "Christmas Run",
            eventPlan: true,
            workoutCount: 1,
            planId: 3, 
            plannedWorkoutTypeDurations: [],
            title: "Training Plan Three",
            planApplications: [
                {
                    appliedPlanId: 21,
                    startDate: "2013-01-02",
                    endDate: "2013-09-10"
                },
                {
                    appliedPlanId: 22,
                    startDate: "2014-01-02",
                    endDate: "2014-09-10"
                }
            ],
        },

        accessRightsLimited: {
            planFutureWorkouts: {
                "accessRightItemDataValue": {"data":"4"},
                "accessRightIdValue":8,
                "accessRightItemDataTypeValue":3,
                "accessRightData":[4]
            },
            canViewPods: {
                "accessRightItemDataValue": {
                    "data":"journal_GroundControl,<SPL1T>,journal_layoutTiled,<SPL1T>,meal_builder,<SPL1T>,meal_macros,<SPL1T>,meal_notes,<SPL1T>,meal_stats,<SPL1T>,pod_CadenceBins,<SPL1T>,pod_calories_difference_over_time,<SPL1T>,pod_criticalPowerBests,<SPL1T>,pod_DailyMetricsReporting,<SPL1T>,pod_DailyMetricsReporting,<SPL1T>,pod_DashboardWelcome,<SPL1T>,pod_equipment,<SPL1T>,pod_FileUpload,<SPL1T>,pod_KilojoulesByWeek,<SPL1T>,pod_lapsAndSplits,<SPL1T>,pod_LongestWorkoutByWeekDistance,<SPL1T>,pod_LongestWorkoutByWeekDuration,<SPL1T>,pod_meal_macronutrients_over_time,<SPL1T>,pod_meanMaxCadence,<SPL1T>,pod_meanMaxCadenceBests,<SPL1T>,pod_meanMaxHeartRateBests,<SPL1T>,pod_meanMaxHR,<SPL1T>,pod_meanMaxPace,<SPL1T>,pod_meanMaxPaceBests,<SPL1T>,pod_meanMaxPower,<SPL1T>,pod_meanMaxSpeed,<SPL1T>,pod_meanMaxSpeedBests,<SPL1T>,pod_MicronutrientReport,<SPL1T>,pod_PaceBins,<SPL1T>,pod_PaceByZones,<SPL1T>,pod_PerformanceManagerChart,<SPL1T>,pod_powerByBins,<SPL1T>,pod_PowerProfileChart,<SPL1T>,pod_RaceReports,<SPL1T>,pod_RouteReporting,<SPL1T>,pod_ShoppingList,<SPL1T>,pod_SpeedBins,<SPL1T>,pod_SpeedByZones,<SPL1T>,pod_TimeInHeartRateZonesByDate,<SPL1T>,pod_TimeInHeartRateZonesByWeek,<SPL1T>,pod_TimeInPowerZonesByDate,<SPL1T>,pod_TimeInPowerZonesByWeek,<SPL1T>,pod_TimeInSpeedZonesByDate,<SPL1T>,pod_TimeInSpeedZonesByWeek,<SPL1T>,pod_workout_summary_over_time,<SPL1T>,pod_WorkoutExtensions,<SPL1T>,pod_WorkoutSummaryReportDistance,<SPL1T>,pod_WorkoutSummaryReportDuration,<SPL1T>,pod_WorkoutSummaryReportTssIF,<SPL1T>,view_Graph,<SPL1T>,view_Map,<SPL1T>,view_Ranges,<SPL1T>,view_Route,<SPL1T>,view_QuadrantAnalysis,<SPL1T>,wo_Comments,<SPL1T>,wo_CriticalPower,<SPL1T>,wo_HeartRateByBins,<SPL1T>,wo_HeartRateByZones,<SPL1T>,wo_MinMaxAvg,<SPL1T>,wo_PowerByZones,<SPL1T>,wo_summary,<SPL1T>,pod_WeatherForecast,<SPL1T>,view_ScatterPlot,<SPL1T>,pod_WKOSummary,<SPL1T>,view_DataGrid,<SPL1T>,pod_meanMaxDistanceBests,<SPL1T>,pod_meanMaxDistance"
                },
                "accessRightIdValue":2,
                "accessRightItemDataTypeValue":5,
                "accessRightData":[
                    "journal_GroundControl",
                    "journal_layoutTiled",
                    "meal_builder",
                    "meal_macros",
                    "meal_notes",
                    "meal_stats",
                    "pod_CadenceBins",
                    "pod_calories_difference_over_time",
                    "pod_criticalPowerBests",
                    "pod_DailyMetricsReporting",
                    "pod_DailyMetricsReporting",
                    "pod_DashboardWelcome",
                    "pod_equipment",
                    "pod_FileUpload",
                    "pod_KilojoulesByWeek",
                    "pod_lapsAndSplits",
                    "pod_LongestWorkoutByWeekDistance",
                    "pod_LongestWorkoutByWeekDuration",
                    "pod_meal_macronutrients_over_time",
                    "pod_meanMaxCadence",
                    "pod_meanMaxCadenceBests",
                    "pod_meanMaxHeartRateBests",
                    "pod_meanMaxHR",
                    "pod_meanMaxPace",
                    "pod_meanMaxPaceBests",
                    "pod_meanMaxPower",
                    "pod_meanMaxSpeed",
                    "pod_meanMaxSpeedBests",
                    "pod_MicronutrientReport",
                    "pod_PaceBins",
                    "pod_PaceByZones",
                    "pod_PerformanceManagerChart",
                    "pod_powerByBins",
                    "pod_PowerProfileChart",
                    "pod_RaceReports",
                    "pod_RouteReporting",
                    "pod_ShoppingList",
                    "pod_SpeedBins",
                    "pod_SpeedByZones",
                    "pod_TimeInHeartRateZonesByDate",
                    "pod_TimeInHeartRateZonesByWeek",
                    "pod_TimeInPowerZonesByDate",
                    "pod_TimeInPowerZonesByWeek",
                    "pod_TimeInSpeedZonesByDate",
                    "pod_TimeInSpeedZonesByWeek",
                    "pod_workout_summary_over_time",
                    "pod_WorkoutExtensions",
                    "pod_WorkoutSummaryReportDistance",
                    "pod_WorkoutSummaryReportDuration",
                    "pod_WorkoutSummaryReportElevation",
                    "expando_DataEditing",
                    "pod_WorkoutSummaryReportTssIF",
                    "view_Graph",
                    "view_Map",
                    "view_Ranges",
                    "view_Route",
                    "view_QuadrantAnalysis",
                    "wo_Comments",
                    "wo_CriticalPower",
                    "wo_HeartRateByBins",
                    "wo_HeartRateByZones",
                    "wo_MinMaxAvg",
                    "wo_PowerByZones",
                    "wo_summary",
                    "pod_WeatherForecast",
                    "view_ScatterPlot",
                    "pod_WKOSummary",
                    "view_DataGrid",
                    "pod_meanMaxDistanceBests",
                    "pod_meanMaxDistance"
                ]
            },
            canUsePods: {
                "accessRightItemDataValue":
                    {
                        "data":"meal_builder,<SPL1T>,meal_macros,<SPL1T>,meal_notes,<SPL1T>,meal_stats,<SPL1T>,pod_calories_difference_over_time,<SPL1T>,pod_DashboardWelcome,<SPL1T>,pod_equipment,<SPL1T>,pod_meal_macronutrients_over_time,<SPL1T>,pod_ShoppingList,<SPL1T>,pod_workout_summary_over_time,<SPL1T>,pod_WorkoutExtensions,<SPL1T>,wo_Comments,<SPL1T>,wo_HeartRateByZones,<SPL1T>,wo_MinMaxAvg,<SPL1T>,wo_PowerByZones,<SPL1T>,wo_summary"
                    },
                "accessRightIdValue":3,
                "accessRightItemDataTypeValue":5,
                "accessRightData":[
                    "meal_builder",
                    "meal_macros",
                    "meal_notes",
                    "meal_stats",
                    "pod_calories_difference_over_time",
                    "pod_DashboardWelcome",
                    "pod_equipment",
                    "pod_meal_macronutrients_over_time",
                    "pod_ShoppingList",
                    "pod_workout_summary_over_time",
                    "pod_WorkoutExtensions",
                    "wo_Comments",
                    "wo_HeartRateByZones",
                    "wo_MinMaxAvg",
                    "wo_PowerByZones",
                    "wo_summary"
                ]
            }
        },

        accessRights: {
            planFutureWorkouts: {
                "accessRightItemDataValue": {"data":"4"},
                "accessRightIdValue":8,
                "accessRightItemDataTypeValue":3,
                "accessRightData":[4]
            },
            canViewPods: {
                "accessRightItemDataValue": {
                    "data":"journal_GroundControl,<SPL1T>,journal_layoutTiled,<SPL1T>,meal_builder,<SPL1T>,meal_macros,<SPL1T>,meal_notes,<SPL1T>,meal_stats,<SPL1T>,pod_CadenceBins,<SPL1T>,pod_calories_difference_over_time,<SPL1T>,pod_criticalPowerBests,<SPL1T>,pod_DailyMetricsReporting,<SPL1T>,pod_DailyMetricsReporting,<SPL1T>,pod_DashboardWelcome,<SPL1T>,pod_equipment,<SPL1T>,pod_FileUpload,<SPL1T>,pod_KilojoulesByWeek,<SPL1T>,pod_lapsAndSplits,<SPL1T>,pod_LongestWorkoutByWeekDistance,<SPL1T>,pod_LongestWorkoutByWeekDuration,<SPL1T>,pod_meal_macronutrients_over_time,<SPL1T>,pod_meanMaxCadence,<SPL1T>,pod_meanMaxCadenceBests,<SPL1T>,pod_meanMaxHeartRateBests,<SPL1T>,pod_meanMaxHR,<SPL1T>,pod_meanMaxPace,<SPL1T>,pod_meanMaxPaceBests,<SPL1T>,pod_meanMaxPower,<SPL1T>,pod_meanMaxSpeed,<SPL1T>,pod_meanMaxSpeedBests,<SPL1T>,pod_MicronutrientReport,<SPL1T>,pod_PaceBins,<SPL1T>,pod_PaceByZones,<SPL1T>,pod_PerformanceManagerChart,<SPL1T>,pod_powerByBins,<SPL1T>,pod_PowerProfileChart,<SPL1T>,pod_RaceReports,<SPL1T>,pod_RouteReporting,<SPL1T>,pod_ShoppingList,<SPL1T>,pod_SpeedBins,<SPL1T>,pod_SpeedByZones,<SPL1T>,pod_TimeInHeartRateZonesByDate,<SPL1T>,pod_TimeInHeartRateZonesByWeek,<SPL1T>,pod_TimeInPowerZonesByDate,<SPL1T>,pod_TimeInPowerZonesByWeek,<SPL1T>,pod_TimeInSpeedZonesByDate,<SPL1T>,pod_TimeInSpeedZonesByWeek,<SPL1T>,pod_workout_summary_over_time,<SPL1T>,pod_WorkoutExtensions,<SPL1T>,pod_WorkoutSummaryReportDistance,<SPL1T>,pod_WorkoutSummaryReportDuration,<SPL1T>,pod_WorkoutSummaryReportTssIF,<SPL1T>,view_Graph,<SPL1T>,view_Map,<SPL1T>,view_Ranges,<SPL1T>,view_Route,<SPL1T>,view_QuadrantAnalysis,<SPL1T>,wo_Comments,<SPL1T>,wo_CriticalPower,<SPL1T>,wo_HeartRateByBins,<SPL1T>,wo_HeartRateByZones,<SPL1T>,wo_MinMaxAvg,<SPL1T>,wo_PowerByZones,<SPL1T>,wo_summary,<SPL1T>,pod_WeatherForecast,<SPL1T>,view_ScatterPlot,<SPL1T>,pod_WKOSummary,<SPL1T>,view_DataGrid,<SPL1T>,pod_meanMaxDistanceBests,<SPL1T>,pod_meanMaxDistance"
                },
                "accessRightIdValue":2,
                "accessRightItemDataTypeValue":5,
                "accessRightData":[
                    "journal_GroundControl",
                    "journal_layoutTiled",
                    "meal_builder",
                    "meal_macros",
                    "meal_notes",
                    "meal_stats",
                    "pod_CadenceBins",
                    "pod_calories_difference_over_time",
                    "pod_criticalPowerBests",
                    "pod_DailyMetricsReporting",
                    "pod_DailyMetricsReporting",
                    "pod_DashboardWelcome",
                    "pod_equipment",
                    "pod_FileUpload",
                    "pod_KilojoulesByWeek",
                    "pod_lapsAndSplits",
                    "pod_LongestWorkoutByWeekDistance",
                    "pod_LongestWorkoutByWeekDuration",
                    "pod_meal_macronutrients_over_time",
                    "pod_meanMaxCadence",
                    "pod_meanMaxCadenceBests",
                    "pod_meanMaxHeartRateBests",
                    "pod_meanMaxHR",
                    "pod_meanMaxPace",
                    "pod_meanMaxPaceBests",
                    "pod_meanMaxPower",
                    "pod_meanMaxSpeed",
                    "pod_meanMaxSpeedBests",
                    "pod_MicronutrientReport",
                    "pod_PaceBins",
                    "pod_PaceByZones",
                    "pod_PerformanceManagerChart",
                    "pod_powerByBins",
                    "pod_PowerProfileChart",
                    "pod_RaceReports",
                    "pod_RouteReporting",
                    "pod_ShoppingList",
                    "pod_SpeedBins",
                    "pod_SpeedByZones",
                    "pod_TimeInHeartRateZonesByDate",
                    "pod_TimeInHeartRateZonesByWeek",
                    "pod_TimeInPowerZonesByDate",
                    "pod_TimeInPowerZonesByWeek",
                    "pod_TimeInSpeedZonesByDate",
                    "pod_TimeInSpeedZonesByWeek",
                    "pod_workout_summary_over_time",
                    "pod_WorkoutExtensions",
                    "pod_WorkoutSummaryReportDistance",
                    "pod_WorkoutSummaryReportDuration",
                    "pod_WorkoutSummaryReportElevation",
                    "expando_DataEditing",
                    "pod_WorkoutSummaryReportTssIF",
                    "view_Graph",
                    "view_Map",
                    "view_Ranges",
                    "view_Route",
                    "view_QuadrantAnalysis",
                    "wo_Comments",
                    "wo_CriticalPower",
                    "wo_HeartRateByBins",
                    "wo_HeartRateByZones",
                    "wo_MinMaxAvg",
                    "wo_PowerByZones",
                    "wo_summary",
                    "pod_WeatherForecast",
                    "view_ScatterPlot",
                    "pod_WKOSummary",
                    "view_DataGrid",
                    "pod_meanMaxDistanceBests",
                    "pod_meanMaxDistance"
                ]
            },
            canUsePodsLimited: {
                "accessRightItemDataValue":
                    {
                        "data":"meal_builder,<SPL1T>,meal_macros,<SPL1T>,meal_notes,<SPL1T>,meal_stats,<SPL1T>,pod_calories_difference_over_time,<SPL1T>,pod_DashboardWelcome,<SPL1T>,pod_equipment,<SPL1T>,pod_meal_macronutrients_over_time,<SPL1T>,pod_ShoppingList,<SPL1T>,pod_workout_summary_over_time,<SPL1T>,pod_WorkoutExtensions,<SPL1T>,wo_Comments,<SPL1T>,wo_HeartRateByZones,<SPL1T>,wo_MinMaxAvg,<SPL1T>,wo_PowerByZones,<SPL1T>,wo_summary"
                    },
                "accessRightIdValue":3,
                "accessRightItemDataTypeValue":5,
                "accessRightData":[
                    "meal_builder",
                    "meal_macros",
                    "meal_notes",
                    "meal_stats",
                    "pod_calories_difference_over_time",
                    "pod_DashboardWelcome",
                    "pod_equipment",
                    "pod_meal_macronutrients_over_time",
                    "pod_ShoppingList",
                    "pod_workout_summary_over_time",
                    "pod_WorkoutExtensions",
                    "wo_Comments",
                    "wo_HeartRateByZones",
                    "wo_MinMaxAvg",
                    "wo_PowerByZones",
                    "wo_summary"
                ]
            },
            canUsePodsFull: {
                "accessRightItemDataValue":
                    {
                        "data":"meal_builder,<SPL1T>,meal_macros,<SPL1T>,meal_notes,<SPL1T>,meal_stats,<SPL1T>,pod_calories_difference_over_time,<SPL1T>,pod_DashboardWelcome,<SPL1T>,pod_equipment,<SPL1T>,pod_meal_macronutrients_over_time,<SPL1T>,pod_ShoppingList,<SPL1T>,pod_workout_summary_over_time,<SPL1T>,pod_WorkoutExtensions,<SPL1T>,wo_Comments,<SPL1T>,wo_HeartRateByZones,<SPL1T>,wo_MinMaxAvg,<SPL1T>,wo_PowerByZones,<SPL1T>,wo_summary"
                    },
                "accessRightIdValue":3,
                "accessRightItemDataTypeValue":5,
                "accessRightData":[
                    "journal_GroundControl",
                    "journal_layoutTiled",
                    "meal_builder",
                    "meal_macros",
                    "meal_notes",
                    "meal_stats",
                    "pod_CadenceBins",
                    "pod_calories_difference_over_time",
                    "pod_criticalPowerBests",
                    "pod_DailyMetricsReporting",
                    "pod_DailyMetricsReporting",
                    "pod_DashboardWelcome",
                    "pod_equipment",
                    "pod_FileUpload",
                    "pod_KilojoulesByWeek",
                    "pod_lapsAndSplits",
                    "pod_LongestWorkoutByWeekDistance",
                    "pod_LongestWorkoutByWeekDuration",
                    "pod_meal_macronutrients_over_time",
                    "pod_meanMaxCadence",
                    "pod_meanMaxCadenceBests",
                    "pod_meanMaxHeartRateBests",
                    "pod_meanMaxHR",
                    "pod_meanMaxPace",
                    "pod_meanMaxPaceBests",
                    "pod_meanMaxPower",
                    "pod_meanMaxSpeed",
                    "pod_meanMaxSpeedBests",
                    "pod_MicronutrientReport",
                    "pod_PaceBins",
                    "pod_PaceByZones",
                    "pod_PerformanceManagerChart",
                    "pod_powerByBins",
                    "pod_PowerProfileChart",
                    "pod_RaceReports",
                    "pod_RouteReporting",
                    "pod_ShoppingList",
                    "pod_SpeedBins",
                    "pod_SpeedByZones",
                    "pod_TimeInHeartRateZonesByDate",
                    "pod_TimeInHeartRateZonesByWeek",
                    "pod_TimeInPowerZonesByDate",
                    "pod_TimeInPowerZonesByWeek",
                    "pod_TimeInSpeedZonesByDate",
                    "pod_TimeInSpeedZonesByWeek",
                    "pod_workout_summary_over_time",
                    "pod_WorkoutExtensions",
                    "pod_WorkoutSummaryReportDistance",
                    "pod_WorkoutSummaryReportDuration",
                    "pod_WorkoutSummaryReportElevation",
                    "expando_DataEditing",
                    "pod_WorkoutSummaryReportTssIF",
                    "view_Graph",
                    "view_Map",
                    "view_Ranges",
                    "view_Route",
                    "view_QuadrantAnalysis",
                    "wo_Comments",
                    "wo_CriticalPower",
                    "wo_HeartRateByBins",
                    "wo_HeartRateByZones",
                    "wo_MinMaxAvg",
                    "wo_PowerByZones",
                    "wo_summary",
                    "pod_WeatherForecast",
                    "view_ScatterPlot",
                    "pod_WKOSummary",
                    "view_DataGrid",
                    "pod_meanMaxDistanceBests",
                    "pod_meanMaxDistance"
                ]
            },
            maximumWorkoutTemplatesInOwnedLibrary: {
                "accessRightItemDataValue": {"data":5},
                "accessRightIdValue": 20,
                "accessRightItemDataTypeValue": 2,
                "accessRightData": 5
            }
        }
    };

    xhrData.defaultTestUserAccessRights = [
        xhrData.accessRights.planFutureWorkouts,
        xhrData.accessRights.maximumWorkoutTemplatesInOwnedLibrary,
        xhrData.accessRights.canViewPods,
        xhrData.accessRights.canUsePodsFull
    ];

    return xhrData;

});